<a href="https://colab.research.google.com/github/SeanLaurea/Linear-Algebra-58020-for-Computer-Engineers/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FINAL EXAM**

Problem 1

In [17]:
import numpy as np
a = np.array([[1, 1, 1],[1, 0, 4],[0, 0, 5]])
print(f'Matrix A: {a}')
print()
b = np.array([[89],[89],[95]])
print(f'Matrix B: {a}')
C = np.linalg.inv(a).dot(b)
print(f'\nInverse of Matrix A:{c}')

Matrix A: [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B: [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:[[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]


Problem 2

In [15]:
import numpy as np
A = np.array([[3,-1,-1],[9,3,-3],[-12,4,-4]])
print(f"Matrix A: {A}")

inv_A = np.linalg.pinv(A)
print(f"Inverse of Matrix A: {inv_A}")
B = np.array([[5],[10],[-20]])
print(f"Matrix A: {A}")

C = np.dot(inv_A, B)
print(f"Dot Product: {C}")
D = np.dot(A, C)
print(f"Checking: {D}")

Matrix A: [[  3  -1  -1]
 [  9   3  -3]
 [-12   4  -4]]
Inverse of Matrix A: [[ 9.19010579e-18  5.55555556e-02 -4.16666667e-02]
 [-5.00000000e-01  1.66666667e-01 -1.24687564e-16]
 [-5.00000000e-01  1.12522954e-16 -1.25000000e-01]]
Matrix A: [[  3  -1  -1]
 [  9   3  -3]
 [-12   4  -4]]
Dot Product: [[ 1.38888889e+00]
 [-8.33333333e-01]
 [ 2.77555756e-15]]
Checking: [[  5.]
 [ 10.]
 [-20.]]


Problem 3

In [11]:
import numpy as np
from scipy.linalg import eig
a = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(a)
b, c = np.linalg.eig(a)
print("The Eigenvalues are: \n",b)
print("The Right Eigenvectors are: \n",c.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The Eigenvalues are: 
 [-1.  3.  2.]
The Right Eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
