<a href="https://colab.research.google.com/github/SeanLaurea/Linear-Algebra-58020-for-Computer-Engineers/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMBER 1**

In [17]:
import numpy as np
G = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[0,1,2,3,4]])
print(G)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 0  1  2  3  4]]


**NUMBER 2**

In [6]:
import numpy as np 
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(A)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


**NUMBER 3**

In [23]:
import numpy as np

u =np.array([[6,1,6],[1,5,2],[6,2,7]])
print(u)
print(" ")

print(np.transpose(u))

[[6 1 6]
 [1 5 2]
 [6 2 7]]
 
[[6 1 6]
 [1 5 2]
 [6 2 7]]


**NUMBER 4**

In [16]:
r=np.array(([[1,2,3],[2,3,3],[3,4,-2]]))
R=(np.linalg.inv(r))
print(R)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


**NUMBER 5**

In [15]:
import numpy as np
v = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(v)
print(np.linalg.det(v))
print(round(np.linalg.det(v)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


**NUMBER 6**

In [14]:
import numpy as np
t= np.array([[5,4,1],[10,9,4],[10,13,15]])
inv_t = np.linalg.inv(t)
print(t)
print()
print(inv_t)

y = np.array([[3,4],[8,8],[19,2]])
x = np.dot(inv_t, y)
print("root = ")
print(x)

z = np.dot(t, x)
print("check = ")
print(z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
root = 
[[ 4.00000000e-01 -2.00000000e+00]
 [-1.66533454e-15  4.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00]]
check = 
[[ 3.  4.]
 [ 8.  8.]
 [19.  2.]]
