<a href="https://colab.research.google.com/github/SeanLaurea/Linear-Algebra-58020-for-Computer-Engineers/blob/main/Midterm_Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
A = np.array([[5,7,3],[3,5,1],[6,8,2]])
B = (np.linalg.inv(A))
print (B)

[[-0.25 -1.25  1.  ]
 [ 0.    1.   -0.5 ]
 [ 0.75 -0.25 -0.5 ]]


In [7]:
A = np.array([[5,7,3],[3,5,1],[6,8,2]])
print (A)
B = np.transpose(A)
print (B)

[[5 7 3]
 [3 5 1]
 [6 8 2]]
[[5 3 6]
 [7 5 8]
 [3 1 2]]
