<a href="https://colab.research.google.com/github/SeanLaurea/Linear-Algebra-58020-for-Computer-Engineers/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROBLEM 1**

**Answer for Problem 1 A**

In [58]:
import numpy as wr
W = wr.array([[1,-3],[2,-2],[3,1]])
Y = wr.array ([[1,2,0],[0,-1,-2]])
print(np.dot(W,Y))

[[ 1  5  6]
 [ 2  6  4]
 [ 3  5 -2]]


**Answer for Problem 1 B**

In [17]:
Z = wr.array([[0,1],[2,3]])
Z = wr.array([[0,1],[2,3]])
b = Z+Z
print(b)

[[0 2]
 [4 6]]


**Answer for Problem 1 C**

In [21]:
X = wr.array([[[3,2,1],[-1,2,3],[2,-1,1]]])
print(3*X)


[[[ 9  6  3]
  [-3  6  9]
  [ 6 -3  3]]]


**PROBLEM 2**

**Problem 2 A**

In [61]:
Y = wr.array([[1,2,0],[0,-1,2]])
W = wr.array([[1,-3],[2,-2],[3,1]])
print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


**Problem 2 B**

In [62]:
d = wr.dot(W,Y)
print(wr.subtract(d,X))

[[[-2  3 -7]
  [ 3  4 -7]
  [ 1  6  1]]]


**Problem 2 C**

In [63]:
print(wr.dot(Y,W)-Z^2)


[[ 7 -6]
 [ 0  3]]
